### PR TITLE
Implemented store.all() method

### PR DESCRIPTION
**Pull request by mehmetb**
[store.all()](https://github.com/expressjs/session#storeallcallback) is listed as optional in express-session.

### CODE REVIEW

**Comment by omarryhan** [comment]
Hey Mehmet, thanks a lot for both PRs.

I just merged some old PRs and it appears that there is a conflict with this PR. Sorry, can you resolve them?

**Comment by mehmetb** [comment]
Hey Omar, I merged master into the PR branch and ran the tests. Everything seems to be working 😄

**Comment by omarryhan** [comment]
Awesome! Thanks again :)

**Comment by omarryhan** [comment]
Let's hope @gx0r is around and can release a new version to npm soon.

**Pull request merged**
