### PR TITLE
bump knex to 1.0.2

### PR DESCRIPTION
**Pull request by akoskm**
https://knexjs.org/#changelog

I assume there'll be some CI running when I make the PR, because I think this version upgrade breaks the types.

I just tried to bump knex in one of my projects and got the following error:

```
src/server.tsx:50:3 - error TS2322: Type 'import("/Users/akoskm/Projects/my-project/node_modules/knex/types/index").Knex<any, unknown[]>' is not assignable to type 'import("/Users/akoskm/Projects/my-project/node_modules/connect-session-knex/node_modules/knex/types/index").Knex<any, unknown[]>'.
  Types of property 'raw' are incompatible.
    Type 'import("/Users/akoskm/Projects/my-project/node_modules/knex/types/index").Knex.RawBuilder<any, any>' is not assignable to type 'import("/Users/akoskm/Projects/my-project/node_modules/connect-session-knex/node_modules/knex/types/index").Knex.RawBuilder<any, any>'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'import("/Users/akoskm/Projects/my-project/node_modules/connect-session-knex/node_modules/knex/types/index").Knex.Value' is not assignable to type 'import("/Users/akoskm/Projects/my-project/node_modules/knex/types/index").Knex.Value'.
          Type 'Raw<any>' is not assignable to type 'Value'.
            Type 'import("/Users/akoskm/Projects/my-project/node_modules/connect-session-knex/node_modules/knex/types/index").Knex.Raw<any>' is not assignable to type 'import("/Users/akoskm/Projects/my-project/node_modules/knex/types/index").Knex.Raw<any>'.
              The types returned by 'generateDdlCommands()' are incompatible between these types.
                Type 'Promise<{ pre: string[]; sql: string[]; post: string[]; }>' is not assignable to type 'Promise<{ pre: string[]; sql: string[]; check: string; post: string[]; }>'.
                  Property 'check' is missing in type '{ pre: string[]; sql: string[]; post: string[]; }' but required in type '{ pre: string[]; sql: string[]; check: string; post: string[]; }'.

50   knex,
     ~~~~

  node_modules/knex/types/index.d.ts:1941:68
    1941     generateDdlCommands(): Promise<{ pre: string[], sql: string[], check: string | null, post: string[] }>;
                                                                            ~~~~~
    'check' is declared here.
  node_modules/connect-session-knex/typings/index.d.ts:8:9
    8         knex?: Knex;
              ~~~~
    The expected type comes from property 'knex' which is declared here on type 'ConfigType'

[10:46:20 AM] Found 1 error. Watching for file changes.
```

Happening on this line:
```
const store = new KnexSessionStore({
  knex, // <- this is where the ts compiler complains about the types
  tablename: "sessions"
});
```

Changing:
https://github.com/gx0r/connect-session-knex/blob/8a8459307d8fe9c7c2b90702de55d8fd9059c04c/typings/index.d.ts#L1
to
```
import Knex from 'knex';
```
solves this issue.

### CODE REVIEW

**Comment by akoskm** [comment]
@gx0r let me know if I have to add anything else to this PR!

**Comment by gx0r** [comment]
Thanks!

**Comment by akoskm** [comment]
@gx0r can we create a release including this change?

**Comment by gx0r** [comment]
Yes, been ill. Will release soon.

**Pull request merged**
